import streamlit as st
import pandas as pd
import random
from datetime import datetime

st.title("AI MindShield Emotion Dashboard")

uploaded_file = st.file_uploader("Upload your emotion_logs.csv from Android app", type=["csv"])

if uploaded_file:
    df = pd.read_csv(uploaded_file)
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    st.write("### Emotion Logs")
    st.dataframe(df)

    st.write("### Emotion Distribution")
    st.bar_chart(df['emotion'].value_counts())

    st.write("### Emotions Over Time")
    df = df.set_index('timestamp')

def generate_fixed_csv():
    emotions_fixed = ['happy', 'neutral', 'sad', 'angry']
    genders = ['Male', 'Female']
    mentalities_fixed = {
        'happy': 'Calm & Productive',
        'neutral': 'Stable & Observant',
        'sad': 'Distracted & Low Mood',
        'angry': 'Aggressive & Risky'
    }
    rows_fixed = []
    start_time = datetime.now() - timedelta(hours=1)
    for i in range(30):
        time = start_time + timedelta(minutes=i * 2)
        gender = random.choice(genders)
        emotion = random.choice(emotions_fixed)
        mentality = mentalities_fixed[emotion]
        rows_fixed.append({
            'timestamp': time.strftime('%Y-%m-%d %H:%M:%S'),
            'gender': gender,
            'emotion': emotion,
            'mentality': mentality
        })
    df_fixed = pd.DataFrame(rows_fixed)
    df_fixed.to_csv("emotion_logs_fixed.csv", index=False)
    st.success("Fixed emotion_logs.csv generated!")

if st.button("Generate Fixed emotion_logs.csv"):
    generate_fixed_csv()

else:
    st.info("Upload the 'emotion_logs.csv' file generated by the Android app to see emotion analytics.")
