import streamlit as st
import pandas as pd
from datetime import datetime

st.title("AI MindShield Emotion Dashboard")

uploaded_file = st.file_uploader("Upload your emotion_logs.csv from Android app", type=["csv"])

if uploaded_file:
    df = pd.read_csv(uploaded_file)
    df['timestamp'] = pd.to_datetime(df['timestamp'])
    st.write("### Emotion Logs")
    st.dataframe(df)

    st.write("### Emotion Distribution")
    st.bar_chart(df['emotion'].value_counts())

    st.write("### Emotions Over Time")
    df = df.set_index('timestamp')
    st.line_chart(df['emotion'].apply(lambda e: {'happy':3,'neutral':2,'sad':1,'angry':0}[e]))
else:
    st.info("Upload the 'emotion_logs.csv' file generated by the Android app to see emotion analytics.")
